-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: BocksBox, v2 by djdude167@gmail.com ******



-- ************************************** `product_details`

CREATE TABLE `product_details`
(
 `id`          int NOT NULL ,
 `name`        linestring NOT NULL ,
 `desc_sm`     linestring NOT NULL ,
 `desc_lg`     multilinestring NOT NULL ,
 `nutrition`   int NOT NULL ,
 `ingredients` json NOT NULL ,
 `facts`       json NOT NULL ,
 `tags`        json NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`nutrition`),
CONSTRAINT `FK_1` FOREIGN KEY `FK_1` (`nutrition`) REFERENCES `nutrition` (`id_1`)
);






